apiVersion: v1
kind: Pod
metadata:
  name: aws-sam-pod
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: lambda
    image: lambci/lambda
    imagePullPolicy: Never
    args:
      - echo
      - "hello world"